# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'# add the Firebase pod for Google Analytics

# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
target 'firebase-test' do
  # Comment the next line if you don't want to use dynamic frameworksvxfdsassada
  use_frameworks!
  pod 'Firebase/Analytics'
  pod 'FirebaseUI/Auth'
  
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Facebook'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'GoogleSignIn'

  # Pods for firebase-test

end
